"use client";
import { useState } from "react";
import Modal from "./components/Modal";
import Nav from "./components/Nav";
import "./globals.css";
const metadata = {
  title: "Achyut Thapa",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  const [modal, setModal] = useState(true);
  const handleClick = () => {
    setModal(!modal);
  };
  return (
    <html lang="en">
      <body className="bg-slate-700">
        <Nav handleClick={handleClick} />
        <Modal isOpen={modal} setModal={setModal} />
        {children}
      </body>
    </html>
  );
}
